### ISSUE TITLE
Postgres version update 12 ->13

### ISSUE THREAD

**Issue by wderuijter** [ualex73/dsmr-reader-docker#2]
Hey @ualex73 , watchtower has updates postgres to version 13. It causes this error in the db-dsmr container:
`2020-09-25 06:27:46.978 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1).`

**Comment by ualex73** [comment]
Yes, i noticed also upgrading Postgres to a higher version is a b*tch. I tried to find an "easy" (and/or straight forward) upgrade path, but it doesn't seem to exist. Last time I exported everything to text/sql format, changes the postgres version and reloaded the data again (following the steps on my page).

**Comment by wderuijter** [comment]
Thanks @ualex73 but unfortunatly exporting with `docker exec -t dsmrdb pg_dumpall -c -U postgres > /tmp/dump_date +%d-%m-%Y""%H%M%S.sql` does not work because container keeps restarting due to the error.
`Error response from daemon: Container de02ad5b9382c0046d2457d7551198bff6a7a26e0c2213661dd38a2ee4a92e92 is restarting` because:
`
2020-09-25 10:03:21.079 UTC [1] FATAL:  database files are incompatible with server
2020-09-25 10:03:21.079 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.0 (Debian 13.0-1.pgdg100+1)`

**Comment by ualex73** [comment]
You need to first rollback to the previous postgres 12 image (and container), before you can do this.

**Comment by wderuijter** [comment]
Thanks @ualex73. Rolled back and works.
