### ISSUE TITLE
Nieuwste image start niet meer

### ISSUE THREAD

**Issue by wburgers** [ualex73/dsmr-reader-docker#4]
De nieuwste versie van deze docker image wil niet opstarten.
Ik heb versie arm32v6-4.11.0 maar weer teruggezet op mijn raspberry pi (2).

De oude versie (arm32v6-4.11.0) zegt dit in de logs:
```
2021-03-04 11:32:30
Start DSMR Reader - Mode=SERVER
Executing '/usr/bin/pg_isready -h dsmr_db -p 5432 -U dsmrreader -d dsmrreader -t 1'
Connected to database successfully
```

De nieuwe versie (latest) zegt het volgende:
```
7889-10-26 08:19:36
Start DSMR Reader - Mode=SERVER
Executing '/usr/bin/pg_isready -h dsmr_db -p 5432 -U dsmrreader -d dsmrreader -t 1'
...........................................................
```

Het lijkt alsof de datum/tijd niet klopt.
Is er iets gewijzigd aan de image?

**Comment by ualex73** [comment]
Is het probleem nog steeds met v4.13.0?

**Comment by wburgers** [comment]
Ja, met de latest image (van 3 dagen geleden) zie ik ook weer in de logs:

```
7889-10-01 14:23:20
Start DSMR Reader - Mode=SERVER
Executing '/usr/bin/pg_isready -h dsmrdb -p 5432 -U dsmrreader -d dsmrreader -t 1'
```

Dus een datum van 7889-10-01
Ik heb ook geprobeerd om de timezone en localtime via een volume te mounten in de container.
Dat schijnt soms nog wel eens te helpen.
```
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
Maar ook dat werkt niet helaas.

**Comment by Yoghoo** [comment]
Hier helaas hetzelfde probleem met de laatste versie (zelfde output). Draai nu weer amd64-4.12.0 en deze werkt goed. 

Als je meer info nodig hebt: let me know.

**Comment by Yoghoo** [comment]
Zie dat er een nieuwe versie op Docker Hub staat. Is dit probleem verholpen of zit het er nog steeds in?

**Comment by Yoghoo** [comment]
Weer een nieuwe versie die nog steeds niet werkt. Jammer. Voor iedereen die nog steeds problemen heeft raad ik aan om over te stappen naar een andere docker image. Die van xirixiz/dsmr-reader-docker werkt perfect en wordt wat beter onderhouden.

**Comment by ualex73** [comment]
Ik heb zelf geen Pi2, maar volgens mij was het een "rotte" python:alpine versie :-( Zie de volgende link:
https://raspberrypi.stackexchange.com/questions/121159/docker-alpinelatest-image-fails-to-get-date-so-everything-fails

Er wordt nu een nieuwe image gebouwd met v3.12, zodra deze gereed is, dan laat ik het weer weten.

**Comment by ualex73** [comment]
Ok, de v4.15 voor arm32v6 is opnieuw geüpload naar hub.docker.com en deze werkt nu wel goed (datum is nu vandaag, niet in het verre verleden/toekomst). Graag hoor ik of het nu is opgelost.

**Comment by ualex73** [comment]
Nog wat meer achtergrond informatie waarom het niet werkte:
https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-762542148

(er lijken nu veel broken images te zijn op hub.docker.com door deze aanpassing :-()

**Comment by wburgers** [comment]
Yess, hij werkt!
Balen dat alleen deze bij mij stuk ging, anders had ik zelf misschien ook eerder de link gelegd naar een stukke base image.
Bedankt voor het uitzoeken!
Overigens is jouw image iets kleiner dan die van xirixiz. Een pi2 kan redelijk traag worden van het extracten van een image, dus hoe kleiner hoe beter. Ik blijf voorlopig bij deze.

**Comment by ualex73** [comment]
@wburgers dank je voor de bevestiging dat het nu weer werkt.

Ik doe het bouwen van de arm images op mijn Ubuntu (amd64) middels QEMU, en hierdoor kan ik het initieel niet reproduceren. Het onderliggende OS (Ubuntu 64-bit) voor Docker heeft dus geen "probleem" met de alpine 3.13, alleen als je dit draait op Raspbian (alle versies lijkt het), dan toont het probleem zich. xirixiz gebruikt ook Alpine, mogelijk was hij uiteindelijk ook tegen dit probleem aangelopen.
BTW - kleiner krijgen dan dit lukt niet ;-)

**Comment by Yoghoo** [comment]
Kleine opmerking: ik draaide dit onder Ubuntu 64 bit met Docker en had dit probleem ook. Dus was niet alleen met Raspbian.

**Comment by ualex73** [comment]
@bvrielink heb je dit probleem nog steeds op Ubuntu?

Volgens de alpine releasenote zou Ubuntu niet geimpact mogen zijn. De releasenotes zeggen:
_Therefore, the following platforms are not suitable as Docker hosts for 32-bit Alpine Linux 3.13.0, due to containing out-of-date libseccomp: Amazon Linux 1 or 2, CentOS 7 or 8, Debian stable without debian-backports, Raspbian stable, Ubuntu 14.04 or earlier, and Windows. This applies regardless of whether the Linux distribution Docker packages or separate Docker package repositories are used._

Maar het zou aan de Docker versie kunnen liggen:
_Therefore, Alpine Linux 3.13.0 requires the host Docker to be version **19.03.9** (which contains backported moby commit 89fabf0) or greater and the host libseccomp to be version 2.4.2 (which contains backported libseccomp commit bf747eb) or greater. Docker for Windows issue 8326 tracks the process of updating libseccomp in Docker for Windows._

**Comment by Yoghoo** [comment]
Dit zijn mijn versies:

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-70-generic x86_64)
Docker version 20.10.5, build 55c4c88

Ik neem aan dat het opgelost is als het nu werkt Raspbian. Kan het momenteel helaas niet testen aangezien ik voorlopig de image van de concurrent gebruik. :) Deze heeft een paar handige opties als vacuum en suppress storage warnings die ik niet kan terugvinden in deze docker image.

**Comment by ualex73** [comment]
De Ubuntu/Docker versie zouden moeten werken met Alpine 3.13, dus da's raar.

De suppress warning zit in DSMR, niet in de docker image ;-) Deze kan je onderdrukken door de volgende environment variable te setten (heb ik ook gedaan):
_DSMRREADER_SUPPRESS_STORAGE_SIZE_WARNINGS=True_

Alle environment variabelen kan je vinden in de volgende link: https://dsmr-reader.readthedocs.io/nl/v4/reference/env-settings.html (wordt door alle docker images ondersteunt, dus Xirixiz en die van mij)

Ja, vacuum zit wel in de andere image ... maar die hoef je niet altijd te draaien ;)

Maar goed, als je het test, dan hoor ik graag het eindresultaat.

**Comment by wburgers** [comment]
Home Assistant werkte ook niet meer na de 2021.7.0 update (ook HA is overgegaan op de nieuwste alpine image lijkt het...).

Nu heb ik toch maar de moeite genomen om het volgende uit te voeren:
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
Wel jammer dat de package repo's van de pi zo achterlopen.

Na het installeren van de nieuwste libseccomp2 én de nieuwste docker engine werkt het prima.
Dus wellicht kan nu toch de overstap gemaakt worden naar de nieuwste alpine image @ualex73?
Dan kun je eventueel verwijzen naar de blog post of dit issue in de changelog voor andere mensen met problemen.

**Comment by ualex73** [comment]
@wburgers  Dan je voor de informatie, ik ga er binnenkort naar kijken en hopelijk kunnen we dan weer naar de laatste Alpine.

**Comment by wburgers** [comment]
@ualex73 Heb je dit ooit nog teruggezet naar de latest versie van alpine in plaats van een fixed versie?

**Comment by ualex73** [comment]
Ik gebruik nu de laatste versie van Alpine, dus je moet op Raspbian/Debian 11 zitten of de patch uitvoeren die op de hoofdpagina staat.

**Comment by wburgers** [comment]
Dan kan deze wel dicht 😉
